apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: devops-tools
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/rambabu1295/kubernetes-kaniko"
    - "--destination=ramdocker/kaniko-test-image:1.0"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    namespace: devops-tools
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json