apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: mgit/base:kaniko-executor-debug-stable
    args:
    - "--context=git://github.com/scriptcamp/kubernetes-kaniko"
    - "--destination=ramdocker/kaniko-test-image:1.0"
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
        - key: .dockerconfigjson
          path: config.json